apiVersion: v1
kind: Pod
metadata:
  name: default-resources-demo-3
spec:
  containers:
  - name: default-resources-cont
    image: httpd:2.4
    resources:
      requests:
        memory: "0.4Gi"
        cpu: 0.6
 