kind: Deployment
apiVersion:	apps/v1
metadata:
  name: kdemo-dep
spec:
  replicas: 3
  selector:
   matchLabels:
    name: kdemo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 20
  template:
    metadata:
      labels:
        name: kdemo
    spec:
      containers:
      - name: kdemo
        image: apprenda/kdemo:v2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
      terminationGracePeriodSeconds: 1
