apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redis
    role: slave
  name: redis-slave
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - image: kubernetes/redis-slave:v2
        imagePullPolicy: IfNotPresent
        name: redis-slave
        ports:
        - containerPort: 6379
          name: redis-server
          protocol: TCP