apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:7
        ports:
        - containerPort: 27017
          name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: password
        volumeMounts:
        - mountPath: /data/db
          name: mongo-volume-1
      volumes:
      - emptyDir: {}
        name: mongo-volume-1
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    name: default
    targetPort: mongo

---
apiVersion: v1
kind: Secret
metadata:
  name: database 
type: Opaque
data:
  password: S3ViZXJuZXRlc1RyYWluaW5n