kind: Deployment
apiVersion:	apps/v1
metadata:
  name: article-service
spec:
  replicas: 3
  selector:
   matchLabels:
    app.kubernetes.io/name: article-service
# Set strategy here
...
  template:
    metadata:
      labels:
        app.kubernetes.io/name: article-service
    spec:
      containers:
      - name: article-service
        image: europe-west1-docker.pkg.dev/wsc-kubernetes-training-0/microservices-demo/article-service:0.0.2
        env:
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: database
          - name: MONGODB_URI
            value: mongodb://root:$(MONGODB_PASSWORD)@mongodb:27017
              
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
      terminationGracePeriodSeconds: 1
