version: '3'
services:

  nginx:
    image: nginx
    volumes:
      - "./nginx:/etc/nginx/conf.d"
    ports:
      - "8080:80"
    depends_on:
      - "article-svc"
      - "front-admin"

  front-admin:
    image: "europe-west1-docker.pkg.dev/wsc-kubernetes-training-0/microservices-demo/front-admin:1.0.0"
    depends_on:
      - "article-svc"
    # TODO [1]: Frontend configuration (specify backend location)
    #volumes:

  article-svc:
    image: "europe-west1-docker.pkg.dev/wsc-kubernetes-training-0/microservices-demo/article-service:1.0.0"
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
    depends_on:
      - "mongo"

  mongo:
    image: "mongo:4"
    # TODO [2]: Add persistence
    #volumes:
