{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simplebackend-service.fullname" . }}
  labels:
    app.kubernetes.io/stack: 
      {{ include "simplebackend.fullname" . }}
    {{- include "simpleapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP 
      name: http
  selector:
    app: {{ include "simplebackend.fullname" . }}
{{- end }}
---
{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simplefrontend-service.fullname" . }}
  labels:
    app.kubernetes.io/stack: 
      {{ include "simplefrontend.fullname" . }}
    {{- include "simpleapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "simplefrontend.fullname" . }}
{{- end }}
