apiVersion: v1
kind: Pod
metadata:
 name: prod-pod
 labels:
   app: busybox
spec:
 containers:
 - name: prod
   image: busybox
   args:
    - sleep
    - "3600"
   command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
 tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "prod"
      effect: "NoSchedule"
