---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-api

spec:
  selector:
    matchLabels:
      app: article-api

  template:
    metadata:
      labels:
        app: article-api

    spec:
      containers:
        - image: "europe-west1-docker.pkg.dev/wsc-kubernetes-training-0/microservices-demo/article-service:1.0"
          name: "article-api"
          env: []
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
...
