{{- if .Values.backend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simplebackend-deployment.fullname" . }}
  labels:
    app.kubernetes.io/stack: 
      {{ include "simplebackend.fullname" . }}
    {{- include "simpleapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "simplebackend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "simplebackend.fullname" . }}
    spec:
      containers:
        - name: {{ include "simplebackend.fullname" . }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
{{- end }}
---
{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simplefrontend-deployment.fullname" . }}
  labels:
    app.kubernetes.io/stack: 
      {{ include "simplefrontend.fullname" . }}
    {{- include "simpleapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "simplefrontend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "simplefrontend.fullname" . }}
    spec:
      containers:
        - name: {{ include "simplefrontend.fullname" . }}
          image: 
            "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: BACKEND_URL
              value:  {{ include "simplebackend-service.url" .}}
          ports:
            - name: http
              containerPort: 
                {{ .Values.frontend.image.ports.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}