---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: article-api

spec:
  selector:
    matchLabels:
      app: article-api

  replicas: 2

  template:
    metadata:
      labels:
        app: article-api

    spec:
      containers:
        - image: "alphayax/microservice-demo-article-service:2.0"
          name: "article-api"
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo:27017"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz

---
apiVersion: v1
kind: Service
metadata:
  name: article-api

spec:
  type: ClusterIP
  selector:
    app: article-api
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
...
