version: '3'
services:

  # Article Service
  article-svc:
    image: "europe-west1-docker.pkg.dev/wsc-kubernetes-training-0/microservices-demo/article-service:1.0.0"
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
    depends_on:
      - "mongo"

  # MongoDb
  mongo:
    image: "mongo"

  # Frontend Admin
  frontend-admin:
    image: "europe-west1-docker.pkg.dev/wsc-kubernetes-training-0/microservices-demo/front-admin:1.0.0"
    ports:
      - "8080:80"
    depends_on:
      - "article-svc"
