FROM node:14

LABEL maintainer="Wescale Formation <training@wescale.fr>"

# Create the directory /usr/src/my-app
RUN ...
# Change the current directory to /usr/src/my-app
WORKDIR ...
# Copy the file app.js to the current directory
COPY ...
# Copy the file package.json to to the current directory
COPY ...
# Execute the command: npm install
RUN ...

EXPOSE 8080

CMD ["node", "app.js"]
