version: '3'
services:
  db:
    image: mariadb:10
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress      

  dbadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    environment:
      # To get a working Web preview with Cloud Shell, need to indicate the Cloud Shell proxy public access
      #
      # WEB_HOST is populated for each Cloud Shell instance
      PMA_ABSOLUTE_URI: "https://8000-${WEB_HOST}"
      MYSQL_USERNAME: wordpress
      MYSQL_PASSWORD: wordpress
    depends_on:
      - db

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      # To get a working Web preview with Cloud Shell...
      #
      # Need to indicate the Cloud Shell proxy public access
      # Need to force SSL
      WORDPRESS_CONFIG_EXTRA: |
        define('FORCE_SSL_ADMIN', true);
        define('WP_SITEURL', 'https://8080-${WEB_HOST}' );
        define('DOMAIN_CURRENT_SITE', '8080-${WEB_HOST}' );
        define('WP_HOME', 'https://8080-${WEB_HOST}');
        $$_SERVER['HTTPS'] = 'on';
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_NAME: wordpress
